<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GamesSeeder extends Seeder
{
    public function run(): void
    {
        $games = [

            /* =========================
               RPG
               category_id = 1
             ========================= */
            [
                'title' => 'The Witcher 3: Wild Hunt',
                'description' => 'RPG de mundo abierto con decisiones estratégicas, combates tácticos y misiones ramificadas.',
                'price' => 150000,
                'category_id' => 1,
                'release_date' => '2015-05-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Elder Scrolls V: Skyrim',
                'description' => 'RPG épico con libertad para explorar, combatir y gestionar habilidades, con estrategia en misiones y construcción de personajes.',
                'price' => 200000,
                'category_id' => 1,
                'release_date' => '2011-11-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Baldur\'s Gate 3',
                'description' => 'RPG táctico basado en D&D, con combates por turnos y narrativa ramificada.',
                'price' => 250000,
                'category_id' => 1,
                'release_date' => '2023-08-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Divinity: Original Sin 2',
                'description' => 'RPG cooperativo con estrategia profunda en combates por turnos y elecciones que afectan el mundo.',
                'price' => 180000,
                'category_id' => 1,
                'release_date' => '2017-09-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dragon Age: Inquisition',
                'description' => 'RPG de fantasía con estrategia en batallas tácticas y construcción de alianzas.',
                'price' => 120000,
                'category_id' => 1,
                'release_date' => '2014-11-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fallout: New Vegas',
                'description' => 'RPG postapocalíptico con estrategia en gestión de recursos, facciones y decisiones morales.',
                'price' => 100000,
                'category_id' => 1,
                'release_date' => '2010-10-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kingdoms of Amalur: Re-Reckoning',
                'description' => 'RPG de acción con elementos estratégicos en combates y progresión de habilidades.',
                'price' => 140000,
                'category_id' => 1,
                'release_date' => '2020-09-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pillars of Eternity',
                'description' => 'RPG isométrico con estrategia en combates por turnos y narrativa basada en elecciones.',
                'price' => 160000,
                'category_id' => 1,
                'release_date' => '2015-03-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Disco Elysium',
                'description' => 'RPG narrativo con estrategia en diálogos y resolución de casos, enfocado en la psicología del personaje.',
                'price' => 90000,
                'category_id' => 1,
                'release_date' => '2019-10-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pathfinder: Kingmaker',
                'description' => 'RPG de gestión de reino con estrategia en batallas tácticas y construcción de un dominio.',
                'price' => 130000,
                'category_id' => 1,
                'release_date' => '2018-09-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tyranny',
                'description' => 'RPG estratégico donde lideras un ejército, tomando decisiones tácticas y morales.',
                'price' => 170000,
                'category_id' => 1,
                'release_date' => '2016-11-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Wasteland 3',
                'description' => 'RPG táctico con estrategia en gestión de equipo y combates en un desierto postapocalíptico.',
                'price' => 190000,
                'category_id' => 1,
                'release_date' => '2020-08-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Banner Saga',
                'description' => 'RPG estratégico con narrativa visual y decisiones en viajes y batallas por turnos.',
                'price' => 70000,
                'category_id' => 1,
                'release_date' => '2014-01-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Divinity: Original Sin',
                'description' => 'RPG cooperativo con estrategia en combates por turnos y magia elemental.',
                'price' => 140000,
                'category_id' => 1,
                'release_date' => '2014-06-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Slay the Spire',
                'description' => 'RPG de cartas con estrategia en construcción de mazos y combates por turnos.',
                'price' => 130000,
                'category_id' => 1,
                'release_date' => '2019-01-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
               ESTRATEGIA
               category_id = 2
             ========================= */
            [
                'title' => 'Civilization VI',
                'description' => 'Estrategia de construcción de civilizaciones con RPG en liderazgo y decisiones diplomáticas.',
                'price' => 180000,
                'category_id' => 2,
                'release_date' => '2016-10-21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Total War: Warhammer II',
                'description' => 'Estrategia en tiempo real con RPG en campañas épicas y unidades fantásticas.',
                'price' => 220000,
                'category_id' => 2,
                'release_date' => '2017-09-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Stardew Valley',
                'description' => 'RPG de simulación agrícola con estrategia en gestión de recursos y relaciones sociales.',
                'price' => 50000,
                'category_id' => 2,
                'release_date' => '2016-02-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Crusader Kings III',
                'description' => 'Estrategia dinástica con RPG en narrativa familiar y decisiones históricas.',
                'price' => 250000,
                'category_id' => 2,
                'release_date' => '2020-09-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Europa Universalis IV',
                'description' => 'Estrategia histórica con RPG en diplomacia y construcción de imperios.',
                'price' => 200000,
                'category_id' => 2,
                'release_date' => '2013-08-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hearts of Iron IV',
                'description' => 'Estrategia de guerra mundial con RPG en liderazgo de naciones y eventos históricos.',
                'price' => 190000,
                'category_id' => 2,
                'release_date' => '2016-06-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Age of Empires II: Definitive Edition',
                'description' => 'Estrategia histórica con RPG en construcción de civilizaciones y batallas épicas.',
                'price' => 150000,
                'category_id' => 2,
                'release_date' => '2019-11-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'RimWorld',
                'description' => 'Estrategia de colonia con RPG en historias de colonos y decisiones morales.',
                'price' => 140000,
                'category_id' => 2,
                'release_date' => '2018-10-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Factorio',
                'description' => 'Estrategia de automatización con RPG en exploración y supervivencia.',
                'price' => 160000,
                'category_id' => 2,
                'release_date' => '2020-08-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dwarf Fortress',
                'description' => 'Estrategia de gestión de fortaleza con RPG en historias emergentes.',
                'price' => 170000,
                'category_id' => 2,
                'release_date' => '2006-12-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'XCOM 2',
                'description' => 'Estrategia táctica con RPG en personalización de soldados y misiones.',
                'price' => 110000,
                'category_id' => 2,
                'release_date' => '2016-02-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Heroes of Might and Magic III',
                'description' => 'Estrategia por turnos con RPG en construcción de héroes y exploración de mapas.',
                'price' => 80000,
                'category_id' => 2,
                'release_date' => '1999-02-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Frostpunk',
                'description' => 'Estrategia de supervivencia con elementos RPG en toma de decisiones éticas.',
                'price' => 120000,
                'category_id' => 2,
                'release_date' => '2018-04-24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kingdom: New Lands',
                'description' => 'RPG estratégico de exploración y construcción de reinos.',
                'price' => 60000,
                'category_id' => 2,
                'release_date' => '2016-08-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Into the Breach',
                'description' => 'Estrategia táctica con RPG en personalización de mechas y misiones.',
                'price' => 100000,
                'category_id' => 2,
                'release_date' => '2018-02-27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cities: Skylines',
                'description' => 'Simulación de construcción y gestión de ciudades con detalles profundos en la infraestructura.',
                'price' => 90000,
                'category_id' => 2,
                'release_date' => '2015-03-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
               HIBRIDO (Todos los demás juegos combinados o sin categoría propia)
               category_id = 3
             ========================= */
            [
                'title' => 'Dishonored',
                'description' => 'Acción/Aventura. Un juego sobre la violencia brutal ambientado en un mundo industrial y retrofuturista.',
                'price' => 90000,
                'category_id' => 3,
                'release_date' => '2012-11-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'GTA 5',
                'description' => 'Acción/Aventura. La quinta entrega sandbox de Rockstar Games, con uno de los mundos abiertos más ricos.',
                'price' => 140000,
                'category_id' => 3,
                'release_date' => '2013-09-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Celeste',
                'description' => 'Acción/Plataformas. Una obra maestra de plataformas 2D con trepidante acción y un diseño de niveles increíble.',
                'price' => 70000,
                'category_id' => 3,
                'release_date' => '2018-01-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sekiro Shadows Die Twice',
                'description' => 'Acción/RPG (Soulslike). Acción y aventuras en tercera persona con elementos de rol y el inconfundible estilo de FromSoftware.',
                'price' => 150000,
                'category_id' => 3,
                'release_date' => '2019-03-22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Inside',
                'description' => 'Acción/Puzle/Aventura. Un cautivador mundo oscuro que combina plataformas, puzles y una historia con carga emocional.',
                'price' => 70000,
                'category_id' => 3,
                'release_date' => '2016-06-29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Batman Arkham City',
                'description' => 'Acción/Aventura. Continuación de Arkham Asylum con más libertad de movimiento y una fórmula de juego mejorada.',
                'price' => 60000,
                'category_id' => 3,
                'release_date' => '2011-10-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Assasin’s Creed II',
                'description' => 'Aventura/Acción. Segunda entrega donde encarnaremos a Ezio, un joven noble en el período del Renacimiento Italiano.',
                'price' => 60000,
                'category_id' => 3,
                'release_date' => '2009-11-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Neon White',
                'description' => 'Acción/Aventura. Frenético juego de acción en primera persona sobre el exterminio de demonios en el cielo.',
                'price' => 90000,
                'category_id' => 3,
                'release_date' => '2022-06-16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Metal Gear Solid 5',
                'description' => 'Acción/Sigilo. La última aventura de Snake bajo las órdenes de Hideo Kojima, con elementos de mundo abierto.',
                'price' => 120000,
                'category_id' => 3,
                'release_date' => '2015-09-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Red Dead Redemption 2',
                'description' => 'Acción/Aventura. Videojuego de mundo abierto ambientado en el corazón de América en 1899 con una atmósfera wéstern muy cuidada.',
                'price' => 160000,
                'category_id' => 3,
                'release_date' => '2018-10-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hollow Knight Silksong',
                'description' => 'Aventura/Acción (Metroidvania). Secuela ambiciosa del querido Hollow Knight, con nuevas habilidades y más de un centenar de enemigos.',
                'price' => 80000,
                'category_id' => 3,
                'release_date' => '2025-09-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Witness',
                'description' => 'Puzzle/Aventura. Fascinante aventura ambientada en una misteriosa isla repleta de rompecabezas.',
                'price' => 100000,
                'category_id' => 3,
                'release_date' => '2016-01-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Monkey Island 2',
                'description' => 'Aventura/Point-and-Click. Sencillamente superlativo. Superior artísticamente y una cita ineludible para los aficionados del género.',
                'price' => 80000,
                'category_id' => 3,
                'release_date' => '2010-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Endling',
                'description' => 'Aventura/Supervivencia. Un juego de supervivencia que esconde un mensaje muy necesario desde la perspectiva de una madre zorro.',
                'price' => 90000,
                'category_id' => 3,
                'release_date' => '2022-05-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Immortality',
                'description' => 'Aventura/Narrativo. Una de las obras más originales del año. Difícil de hablar porque cuanto menos se sepa, mejor.',
                'price' => 120000,
                'category_id' => 3,
                'release_date' => '2022-08-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Syberia the world before',
                'description' => 'Aventura/Puzzle. El cuarto episodio de esta veterana serie de aventuras gráficas, protagonizada por Kate Walker.',
                'price' => 150000,
                'category_id' => 3,
                'release_date' => '2022-03-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Beginner’s Guide',
                'description' => 'Aventura/Narrativo. El resultado de un ejercicio de introspección que pocas veces hemos visto en la industria del videojuego.',
                'price' => 40000,
                'category_id' => 3,
                'release_date' => '2015-07-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'What Remains of Edith Finch',
                'description' => 'Aventura/Exploración. Un cuento que aviva nuestra fe en este estilo narrativo gracias a ideas ingeniosas y un gran ritmo.',
                'price' => 50000,
                'category_id' => 3,
                'release_date' => '2017-04-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'A Memoir Blue',
                'description' => 'Aventura/Narrativo. Un videojuego que necesita respirar en libertad y dar lugar a propuestas de diversa índole.',
                'price' => 40000,
                'category_id' => 3,
                'release_date' => '2022-09-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Gone Home',
                'description' => 'Aventura/Drama interactivo. Se ha convertido en uno de los mejores juegos independientes del momento gracias a una historia muy bien planteada.',
                'price' => 40000,
                'category_id' => 3,
                'release_date' => '2013-08-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SILT',
                'description' => 'Aventura/Exploración. Una interesante alternativa a juegos como Limbo o Inside que propone un viaje submarino intrigante y artístico.',
                'price' => 80000,
                'category_id' => 3,
                'release_date' => '2022-05-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SOMA',
                'description' => 'Horror/Sci-fi/Aventura. Un juego que consigue sorprender sin revolucionar el género. Su mejor baza es una genial puesta en escena.',
                'price' => 70000,
                'category_id' => 3,
                'release_date' => '2015-09-22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Detroit Become Human',
                'description' => 'Aventura gráfica/Narrativo. Un juego 100% Quantic Dream, difícil encontrar algo tan potente en su género.',
                'price' => 100000,
                'category_id' => 3,
                'release_date' => '2018-05-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Subnautica',
                'description' => 'Aventura/Supervivencia. Logra, a base de buenas decisiones, construir un survival rico en matices y posibilidades.',
                'price' => 60000,
                'category_id' => 3,
                'release_date' => '2018-01-16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Inazuma Eleven: Victory Road',
                'description' => 'Híbrido RPG/Fútbol. Experiencia híbrida entre RPG y fútbol, con partidos cargados de habilidades especiales.',
                'price' => 280000,
                'category_id' => 3,
                'release_date' => '2025-11-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rayman Legends',
                'description' => 'Plataformas 2D con niveles creativos y cooperativo local.',
                'price' => 70000,
                'category_id' => 3,
                'release_date' => '2013-08-29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ori and the Will of the Wisps',
                'description' => 'Plataformas Metroidvania con una jugabilidad y banda sonora emotivas.',
                'price' => 110000,
                'category_id' => 3,
                'release_date' => '2020-03-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Shovel Knight',
                'description' => 'Plataformas retro 8-bit con jugabilidad desafiante y estética clásica.',
                'price' => 60000,
                'category_id' => 3,
                'release_date' => '2014-06-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cuphead',
                'description' => 'Plataformas Run and Gun con estilo de dibujos animados de los años 30 y desafiantes batallas contra jefes.',
                'price' => 80000,
                'category_id' => 3,
                'release_date' => '2017-09-29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Sims 4',
                'description' => 'Simulación social y de vida con gestión de personajes y construcción de mundos.',
                'price' => 120000,
                'category_id' => 3,
                'release_date' => '2014-09-02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kerbal Space Program',
                'description' => 'Simulación de física espacial y construcción de cohetes.',
                'price' => 100000,
                'category_id' => 3,
                'release_date' => '2015-04-27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Portal 2',
                'description' => 'Puzle en primera persona con física avanzada, portales y narrativa cómica.',
                'price' => 40000,
                'category_id' => 3,
                'release_date' => '2011-04-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Talos Principle',
                'description' => 'Puzle filosófico en primera persona con robótica y acertijos lógicos.',
                'price' => 80000,
                'category_id' => 3,
                'release_date' => '2014-12-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Limbo',
                'description' => 'Puzle/Plataformas con estética en blanco y negro y atmósferas sombrías.',
                'price' => 30000,
                'category_id' => 3,
                'release_date' => '2010-07-21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Beat Saber',
                'description' => 'Juego de ritmo para VR donde cortas bloques al son de la música.',
                'price' => 100000,
                'category_id' => 3,
                'release_date' => '2019-05-21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Guitar Hero III: Legends of Rock',
                'description' => 'Ritmo musical basado en tocar la guitarra en varios escenarios y canciones de rock.',
                'price' => 60000,
                'category_id' => 3,
                'release_date' => '2007-10-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sayonara Wild Hearts',
                'description' => 'Ritmo y acción con estética pop y neon, siguiendo las notas en escenarios oníricos.',
                'price' => 50000,
                'category_id' => 3,
                'release_date' => '2019-09-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Crypt of the NecroDancer',
                'description' => 'Ritmo/Roguelike, donde los movimientos y ataques deben seguir el ritmo de la música.',
                'price' => 70000,
                'category_id' => 3,
                'release_date' => '2015-04-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Last of Us Part II',
                'description' => 'Acción/Aventura de supervivencia con intensa narrativa post-apocalíptica.',
                'price' => 180000,
                'category_id' => 3,
                'release_date' => '2020-06-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'God of War (2018)',
                'description' => 'Acción/Aventura con elementos RPG, centrado en el combate visceral y la exploración nórdica.',
                'price' => 170000,
                'category_id' => 3,
                'release_date' => '2018-04-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Marvel\'s Spider-Man',
                'description' => 'Acción/Aventura de mundo abierto, enfocado en el combate acrobático y la exploración de Nueva York.',
                'price' => 160000,
                'category_id' => 3,
                'release_date' => '2018-09-07',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
               ACCIÓN
               category_id = 4
             ========================= */
            [
                'title' => 'Doom Eternal',
                'description' => 'Shooter en primera persona extremadamente intenso que eleva la acción clásica de Doom a un nuevo nivel.',
                'price' => 150000,
                'category_id' => 4,
                'release_date' => '2020-03-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Devil May Cry 5',
                'description' => 'Juego de acción hack and slash con nuevos enemigos, jugabilidad y gráficos, ambientado en la clásica franquicia de Capcom.',
                'price' => 100000,
                'category_id' => 4,
                'release_date' => '2019-03-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Half-Life: Alyx',
                'description' => 'Videojuego de la saga Half-Life para dispositivos de realidad virtual (VR) con combate inmersivo y acertijos.',
                'price' => 130000,
                'category_id' => 4,
                'release_date' => '2020-03-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Resident Evil 4 Remake',
                'description' => 'Acción y survival horror en tercera persona, con énfasis en el combate dinámico y la gestión de recursos.',
                'price' => 190000,
                'category_id' => 4,
                'release_date' => '2023-03-24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cyberpunk 2077',
                'description' => 'Action-RPG de mundo abierto futurista con intensos combates en primera persona y progresión de habilidades.',
                'price' => 220000,
                'category_id' => 4,
                'release_date' => '2020-12-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Elden Ring',
                'description' => 'Action-RPG de mundo abierto masivo con combate desafiante y exploración profunda.',
                'price' => 250000,
                'category_id' => 4,
                'release_date' => '2022-02-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Halo Infinite',
                'description' => 'Shooter en primera persona de mundo semiabierto con enfoque en la acción y el multijugador.',
                'price' => 180000,
                'category_id' => 4,
                'release_date' => '2021-12-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Call of Duty: Modern Warfare III',
                'description' => 'Shooter en primera persona militar centrado en la acción rápida y los modos multijugador competitivos.',
                'price' => 280000,
                'category_id' => 4,
                'release_date' => '2023-11-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Gears of War 4',
                'description' => 'Shooter en tercera persona con énfasis en la acción de cobertura y el cooperativo.',
                'price' => 120000,
                'category_id' => 4,
                'release_date' => '2016-10-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Borderlands 3',
                'description' => 'Shooter looter en primera persona con elementos RPG, enfocado en el caos y la obtención de armas.',
                'price' => 140000,
                'category_id' => 4,
                'release_date' => '2019-09-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mass Effect Legendary Edition',
                'description' => 'Colección de Action-RPG con énfasis en el combate en tercera persona y decisiones narrativas.',
                'price' => 160000,
                'category_id' => 4,
                'release_date' => '2021-05-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Control',
                'description' => 'Acción en tercera persona con poderes sobrenaturales y exploración de un mundo cambiante.',
                'price' => 90000,
                'category_id' => 4,
                'release_date' => '2019-08-27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bayonetta 3',
                'description' => 'Hack and Slash frenético con énfasis en combos y enfrentamientos épicos.',
                'price' => 150000,
                'category_id' => 4,
                'release_date' => '2022-10-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nier: Automata',
                'description' => 'Action-RPG con jugabilidad variada, incluyendo elementos de shoot-em-up y plataformas.',
                'price' => 130000,
                'category_id' => 4,
                'release_date' => '2017-03-07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DMC: Devil May Cry',
                'description' => 'Reinicio del Hack and Slash, manteniendo la acción estilizada característica de la serie.',
                'price' => 80000,
                'category_id' => 4,
                'release_date' => '2013-01-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
               AVENTURA
               category_id = 5
             ========================= */
            [
                'title' => 'Return of the Obra Dinn',
                'description' => 'Aventura/Puzzle. Descubre qué ha ocurrido con la tripulación del navío mercante en esta aventura en primera persona.',
                'price' => 50000,
                'category_id' => 5,
                'release_date' => '2018-10-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Thimbleweed Park',
                'description' => 'Aventura (Point-and-Click). Obra humilde con buenas historias que ningún aficionado a las aventuras gráficas debería perderse.',
                'price' => 70000,
                'category_id' => 5,
                'release_date' => '2017-03-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Uncharted 4: A Thief\'s End',
                'description' => 'Aventura cinematográfica con exploración, plataformas y tiroteos en tercera persona.',
                'price' => 150000,
                'category_id' => 5,
                'release_date' => '2016-05-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horizon Zero Dawn',
                'description' => 'Aventura de mundo abierto post-apocalíptico con exploración y combate contra máquinas.',
                'price' => 160000,
                'category_id' => 5,
                'release_date' => '2017-02-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Breath of the Wild',
                'description' => 'Aventura de mundo abierto con énfasis en la libertad de exploración, física y puzles ambientales.',
                'price' => 190000,
                'category_id' => 5,
                'release_date' => '2017-03-03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tomb Raider (2013)',
                'description' => 'Aventura de supervivencia que reinicia la saga de Lara Croft, con exploración intensa y acción.',
                'price' => 70000,
                'category_id' => 5,
                'release_date' => '2013-03-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Life is Strange',
                'description' => 'Aventura gráfica narrativa con toma de decisiones y manipulación del tiempo.',
                'price' => 60000,
                'category_id' => 5,
                'release_date' => '2015-01-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Firewatch',
                'description' => 'Aventura narrativa en primera persona sobre la soledad y la naturaleza.',
                'price' => 50000,
                'category_id' => 5,
                'release_date' => '2016-02-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Journey',
                'description' => 'Aventura de exploración atmosférica y multijugador pasivo, centrada en la emoción visual.',
                'price' => 40000,
                'category_id' => 5,
                'release_date' => '2012-03-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Walking Dead (Telltale)',
                'description' => 'Aventura gráfica episódica con fuerte énfasis en decisiones morales y consecuencias.',
                'price' => 80000,
                'category_id' => 5,
                'release_date' => '2012-04-24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Heavy Rain',
                'description' => 'Aventura interactiva basada en Quick Time Events y decisiones que cambian la trama.',
                'price' => 90000,
                'category_id' => 5,
                'release_date' => '2010-02-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Beyond: Two Souls',
                'description' => 'Aventura narrativa sobre una joven conectada a una entidad sobrenatural.',
                'price' => 90000,
                'category_id' => 5,
                'release_date' => '2013-10-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Until Dawn',
                'description' => 'Aventura de horror interactiva donde las decisiones afectan la supervivencia de los personajes.',
                'price' => 110000,
                'category_id' => 5,
                'release_date' => '2015-08-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Death Stranding',
                'description' => 'Aventura de mundo abierto con enfoque en la exploración, la entrega y la conexión social asíncrona.',
                'price' => 180000,
                'category_id' => 5,
                'release_date' => '2019-11-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
               DEPORTES
               category_id = 6
             ========================= */
            [
                'title' => 'EA Sports FC 26',
                'description' => 'Simulador de fútbol de nueva generación que incorpora mejoras tácticas, animaciones fluidas y actualizaciones de plantillas.',
                'price' => 400000,
                'category_id' => 6,
                'release_date' => '2025-09-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'NBA 2K26',
                'description' => 'Entrega anual del reconocido simulador de baloncesto, con física de balón refinada y modo Mi Carrera profundo.',
                'price' => 280000,
                'category_id' => 6,
                'release_date' => '2025-09-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'PGA Tour 2K25',
                'description' => 'Simulador de golf con una recreación minuciosa de campos oficiales y un sistema de control de swing preciso.',
                'price' => 280000,
                'category_id' => 6,
                'release_date' => '2025-02-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Football Manager 2026',
                'description' => 'Título de gestión deportiva centrado en la dirección técnica de clubes profesionales. Ofrece un motor avanzado de simulación.',
                'price' => 240000,
                'category_id' => 6,
                'release_date' => '2025-11-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tony Hawk’s Pro Skater 3+4 (Remake)',
                'description' => 'Versión modernizada de los clásicos del skate con mejoras visuales, controles actualizados y modos competitivos online.',
                'price' => 200000,
                'category_id' => 6,
                'release_date' => '2025-07-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour de France 2025',
                'description' => 'Videojuego de simulación ciclista, concebido para ofrecer una recreación precisa, dinámica y altamente inmersiva de la competición.',
                'price' => 163000,
                'category_id' => 6,
                'release_date' => '2025-06-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Skate (Skate 4)',
                'description' => 'Juego de skateboarding de mundo abierto con físicas realistas y libertad total para realizar trucos.',
                'price' => 100000,
                'category_id' => 6,
                'release_date' => '2025-09-16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rematch',
                'description' => 'Fútbol arcade rápido en formato 5v5 donde se prioriza la acción dinámica y mecánicas simplificadas.',
                'price' => 120000,
                'category_id' => 6,
                'release_date' => '2025-06-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'WWE 2K25',
                'description' => 'Simulador de lucha libre profesional con animaciones realistas, un elenco amplio de superestrellas y modos narrativos.',
                'price' => 280000,
                'category_id' => 6,
                'release_date' => '2025-03-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pro Cycling Manager 25',
                'description' => 'Avanzada simulación de gestión deportiva diseñada para ofrecer una representación detallada del ciclismo profesional.',
                'price' => 160000,
                'category_id' => 6,
                'release_date' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Riders Republic',
                'description' => 'Juego de deportes extremos que incluye ciclismo, esquí, snowboard y wingsuit en un enorme entorno multijugador persistente.',
                'price' => 160000,
                'category_id' => 6,
                'release_date' => '2021-10-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Top Spin 2K25',
                'description' => 'Simulador de tenis con un sistema avanzado de golpes, posicionamiento realista y recreación fiel de torneos internacionales.',
                'price' => 80000,
                'category_id' => 6,
                'release_date' => '2024-04-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Super Mega Baseball 3',
                'description' => 'Béisbol estilizado pero profundo, con físicas robustas, progresión de equipos y modos cooperativos y competitivos.',
                'price' => 180000,
                'category_id' => 6,
                'release_date' => '2020-05-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Golf With Your Friends',
                'description' => 'Mini golf multijugador con circuitos creativos y mecánicas accesibles, ideal para partidas sociales o recreativas.',
                'price' => 40000,
                'category_id' => 6,
                'release_date' => '2016-01-29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Madden NFL 26',
                'description' => 'Simulador de fútbol americano centrado en tácticas, estrategias ofensivas y defensivas, así como recreación fiel de equipos oficiales.',
                'price' => 280000,
                'category_id' => 6,
                'release_date' => '2025-08-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kopanito All-Stars Soccer',
                'description' => 'Fútbol arcade con habilidades especiales, animaciones rápidas y partidas caóticas enfocadas 100% en la diversión.',
                'price' => 24000,
                'category_id' => 6,
                'release_date' => '2016-11-16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Football, Tactics & Glory',
                'description' => 'Mezcla entre fútbol y juegos tácticos por turnos, donde la estrategia supera a la acción directa.',
                'price' => 60000,
                'category_id' => 6,
                'release_date' => '2015-06-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pixel Cup Soccer – Ultimate Edition',
                'description' => 'Fútbol retro con estética pixel art que combina partidos dinámicos con modos de torneo y campaña.',
                'price' => 34000,
                'category_id' => 6,
                'release_date' => '2014-05-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'NBA The Run',
                'description' => 'Baloncesto urbano 3 vs 3 con enfoque competitivo, movimientos ágiles y escenarios callejeros.',
                'price' => 200000,
                'category_id' => 6,
                'release_date' => '2026-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Forza Motorsport',
                'description' => 'Simulador de carreras de alta fidelidad con énfasis en la física de los vehículos y la estrategia de carrera.',
                'price' => 200000,
                'category_id' => 6,
                'release_date' => '2023-10-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Gran Turismo 7',
                'description' => 'Simulador de conducción con una vasta colección de vehículos y modos de juego que celebran la historia del automovilismo.',
                'price' => 220000,
                'category_id' => 6,
                'release_date' => '2022-03-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
               HORROR
               category_id = 7
             ========================= */
            [
                'title' => 'Silent Hill 2 Remake (Horror)',
                'description' => 'Reinterpretación moderna del clásico del survival horror, con gráficos fotorrealistas y narrativa psicológica profunda.',
                'price' => 200000,
                'category_id' => 7,
                'release_date' => '2025-11-21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tormented Souls 2',
                'description' => 'Survival horror tradicional con cámaras fijas, exploración de entornos góticos y acertijos complejos.',
                'price' => 120000,
                'category_id' => 7,
                'release_date' => '2025-10-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Into the Dead: Our Darkest Days',
                'description' => 'Juego de supervivencia 2.5D donde gestionas un grupo de sobrevivientes en una ciudad infestada de zombis.',
                'price' => 100000,
                'category_id' => 7,
                'release_date' => '2025-04-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Directive 8020',
                'description' => 'Horror espacial con énfasis en narrativa y cooperación. Los jugadores exploran una nave afectada por entidades alienígenas hostiles.',
                'price' => 120000,
                'category_id' => 7,
                'release_date' => '2026-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Silent Hill F',
                'description' => 'Nueva entrega con ambientación en Japón de los años 60, centrada en el horror corporal y las alucinaciones.',
                'price' => 280000,
                'category_id' => 7,
                'release_date' => '2025-09-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Echoes of the Living',
                'description' => 'Homenaje al survival horror clásico con cámaras fijas, exploración de entornos góticos y acertijos complejos.',
                'price' => 100000,
                'category_id' => 7,
                'release_date' => '2025-10-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Look Outside',
                'description' => 'Juego de terror psicológico con estética retro, ambientado en entornos perturbadores y situaciones de peligro constante inspiradas en Lovecraft.',
                'price' => 28000,
                'category_id' => 7,
                'release_date' => '2025-03-21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dark Fracture',
                'description' => 'Horror psicológico en primera persona donde la percepción del protagonista se distorsiona y el entorno cambia de forma impredecible.',
                'price' => 80000,
                'category_id' => 7,
                'release_date' => '2025-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Deathground',
                'description' => 'Título cooperativo donde un equipo debe sobrevivir a dinosaurios extremadamente agresivos en entornos oscuros e impredecibles.',
                'price' => 60000,
                'category_id' => 7,
                'release_date' => '2025-10-07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CloverPit',
                'description' => 'Rogue-lite de horror donde el jugador debe avanzar por escenarios llenos de trampas, decisiones morales y amenazas sobrenaturales.',
                'price' => 40000,
                'category_id' => 7,
                'release_date' => '2025-04-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Go Home Annie',
                'description' => 'Investigación paranormal en primera persona basada en mitologías creepypasta, con acertijos y atmósfera opresiva.',
                'price' => 80000,
                'category_id' => 7,
                'release_date' => '2024-12-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cronos: The New Dawn',
                'description' => 'Horror atmosférico centrado en criaturas deformes y escenarios decadentes; combina exploración lenta con momentos de acción intensa.',
                'price' => 180000,
                'category_id' => 7,
                'release_date' => '2025-09-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Zoochosis',
                'description' => 'Simulador de vigilancia nocturna donde debes investigar mutaciones y comportamientos extraños en un zoológico.',
                'price' => 58000,
                'category_id' => 7,
                'release_date' => '2024-09-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Five Nights at Freddy’s: Secret of the Mimic (2025)',
                'description' => 'Juego de horror en primera persona basado en la popular saga Five Nights at Freddy\'s. Explora una mansión inquietante.',
                'price' => 160000,
                'category_id' => 7,
                'release_date' => '2025-06-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'I Hate This Place',
                'description' => 'Título de mundo semiabierto con criaturas sobrenaturales, eventos impredecibles y una ambientación densa y desesperante.',
                'price' => 32000,
                'category_id' => 7,
                'release_date' => '2026-01-29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Heartworm',
                'description' => 'Survival horror retro con cámaras fijas y tono melancólico, centrado en una historia de trauma, pérdida y misterio.',
                'price' => 60000,
                'category_id' => 7,
                'release_date' => '2025-07-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tenebris Somnia',
                'description' => 'Juego híbrido con estética pixel y secuencias live-action que combina investigación, terror corporal y exploración de entornos surrealistas.',
                'price' => 60000,
                'category_id' => 7,
                'release_date' => '2026-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dreamcore (2025)',
                'description' => 'Juego de terror psicológico en primera persona con estética VHS retro y lugares inquietantes que explorar.',
                'price' => 36000,
                'category_id' => 7,
                'release_date' => '2025-01-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Sinking City 2',
                'description' => 'Secuela orientada en el horror lovecraftiano, con exploración de ciudades sumergidas, entidades mitológicas y acertijos detectivescos.',
                'price' => 180000,
                'category_id' => 7,
                'release_date' => '2026-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fatal Frame 2: Crimson Butterfly Remake',
                'description' => 'Actualización del clásico de terror japonés. Enfrentas espíritus usando solo una cámara mística, lo que genera una tensión constante.',
                'price' => 200000,
                'category_id' => 7,
                'release_date' => '2026-03-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Alien: Isolation',
                'description' => 'Survival horror centrado en el sigilo y la constante amenaza de un único y letal Alien.',
                'price' => 90000,
                'category_id' => 7,
                'release_date' => '2014-10-07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Outlast',
                'description' => 'Horror de supervivencia en primera persona donde el jugador solo puede correr y esconderse, utilizando una cámara de visión nocturna.',
                'price' => 50000,
                'category_id' => 7,
                'release_date' => '2013-09-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]; // <-- El arreglo $games TERMINA aquí.

            // COMIENZA EL PROCESO DE LIMPIEZA Y GRABACIÓN (foreach)
        foreach ($games as $gameData) {
            
            $searchKey = ['title' => $gameData['title']];
            
            $insertData = array_merge($gameData, [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            
            unset($insertData['title']); 

            DB::table('games')->updateOrInsert(
                $searchKey,
                $insertData
            );
        }
    }
}

            
            

